# Generated by Django 2.1.3 on 2018-11-17 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card', '0004_gameinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='type',
            field=models.CharField(blank=True, choices=[('c', 'Multiple Choice'), ('w', 'Writing')], help_text='type of game played', max_length=50),
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='cards',
            field=models.ManyToManyField(help_text='all cards used in game.', to='flash_card.FlashCard'),
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='score',
            field=models.IntegerField(help_text='percentage of correct answers in game.', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
