# Generated by Django 2.1.3 on 2018-11-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card', '0007_auto_20181118_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='type',
            field=models.CharField(choices=[('s', 'Short'), ('l', 'Long')], help_text='short or long charactered card.', max_length=20),
        ),
    ]
