# Generated by Django 2.1.3 on 2018-11-26 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card', '0012_auto_20181118_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 26, 21, 1, 15, 695789), null=True),
        ),
    ]
