# Generated by Django 2.1.3 on 2018-11-26 21:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card', '0013_auto_20181126_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 11, 26, 21, 2, 56, 695333, tzinfo=utc), null=True),
        ),
    ]
