# Generated by Django 2.1.3 on 2018-11-26 21:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card', '0014_auto_20181126_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinstance',
            name='time',
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 26, 21, 5, 43, 847502, tzinfo=utc), null=True),
        ),
    ]
