# Generated by Django 2.1.3 on 2018-12-02 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card', '0015_auto_20181126_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 2, 16, 34, 9, 764255, tzinfo=utc), null=True),
        ),
    ]
