# Generated by Django 2.1.3 on 2018-12-02 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card', '0016_auto_20181202_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 2, 16, 42, 28, 179459, tzinfo=utc), null=True),
        ),
    ]
