# Generated by Django 2.1.3 on 2018-12-02 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card', '0017_auto_20181202_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='colour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 2, 16, 44, 41, 31148, tzinfo=utc), null=True),
        ),
    ]
