# Generated by Django 2.1.3 on 2018-12-02 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card', '0019_auto_20181202_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='colour',
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 2, 17, 6, 49, 186400, tzinfo=utc), null=True),
        ),
    ]
