# Generated by Django 2.1.3 on 2018-12-02 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flash_card', '0020_auto_20181202_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='colour',
            field=models.CharField(blank=True, help_text='colour of flash card.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gameinstance',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 2, 17, 13, 15, 241076, tzinfo=utc), null=True),
        ),
    ]
